CREATE TABLE return_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    buyer_id BIGINT NOT NULL,
    reason VARCHAR(100) NOT NULL,
    description VARCHAR(2000),
    evidence_urls JSONB,
    status INTEGER NOT NULL DEFAULT 0,
    seller_note VARCHAR(1000),
    refund_amount NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_return_requests_orders FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_return_requests_users FOREIGN KEY (buyer_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_return_requests_buyer_id ON return_requests (buyer_id);
